# version: '3.9'

networks:
  frontend_network:
  backend_network:
  monitoring:

services:
  frontend:
    container_name: frontend-hometail
    image: frontend-hometail
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    restart: always
    depends_on:
      - backend1
    networks:
      - frontend_network

  backend1:
    container_name: backend-hometail1
    image: backend-hometail
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network
      - monitoring

  backend2:
    container_name: backend-hometail2
    image: backend-hometail
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 4001:4000
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network
      - monitoring

  db:
    image: postgres:14
    restart: always
    env_file:
      - ./backend/.db.env
    ports:
      - "5433:5432"
    volumes:
      - hometail_pg_data:/var/lib/postgresql/data
    networks:
      - backend_network

  nginx:
    container_name: revproxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - frontend_network
      - backend_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3001:3000
    env_file:
      - ./.grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100" # Port มาตรฐานของ Node Exporter
    networks:
      - monitoring # 👈 ต้องอยู่ใน network เดียวกับ Prometheus

volumes:
  hometail_pg_data:
  grafana_data:
