# version: '3.9'

services:
  frontend:
    container_name: frontend-hometail
    image: frontend-hometail
    build:
      context: ./frontend
      dockerfile: frontend.dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NODE_ENV=development # สำหรับ dev
      - CHOKIDAR_USEPOLLING=true
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend-hometail
    image: backend-hometail
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:1234@db:5432/hometail?schema=public
      # port ข้างใน

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: hometail
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - hometail_pg_data:/var/lib/postgresql/data

volumes:
  hometail_pg_data:

