# version: '3.9'

networks:
  frontend_network:
  backend_network:
  monitoring:

services:
  frontend:
    container_name: frontend-hometail
    image: frontend-hometail
    build:
      context: ./frontend
      dockerfile: frontend.dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - NODE_ENV=development # สำหรับ dev
      - CHOKIDAR_USEPOLLING=true
    restart: always
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    container_name: backend-hometail
    image: backend-hometail
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:1234@db:5432/hometail?schema=public
    networks:
      - frontend_network
      - backend_network
      - monitoring

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: hometail
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - hometail_pg_data:/var/lib/postgresql/data
    networks:
      - backend_network

  nginx:
    container_name: revproxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - frontend_network
      - backend_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_USER=grafana_admin
      - GF_SECURITY_ADMIN_PASSWORD=1234
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  hometail_pg_data:
  grafana_data:
